/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,jsx,js}'],
  theme: {
    extend: {
      fontFamily: {
        heading: ['Kanit', 'sans-serif'], // For headings
        body: ['Nunito', 'sans-serif'], // For body text
      },
      colors: {
        light: {
          primary: '#096B5A',
          surfaceTint: '#096B5A',
          onPrimary: '#FFFFFF',
          primaryContainer: '#A1F2DC',
          onPrimaryContainer: '#00201A',
          secondary: '#4B635C',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#CDE8DF',
          onSecondaryContainer: '#07201A',
          tertiary: '#426277',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#C7E7FF',
          onTertiaryContainer: '#001E2E',
          error: '#BA1A1A',
          onError: '#FFFFFF',
          errorContainer: '#FFDAD6',
          onErrorContainer: '#410002',
          background: '#F5FBF7',
          onBackground: '#171D1B',
          surface: '#F5FBF7',
          onSurface: '#171D1B',
          surfaceVariant: '#DBE5E0',
          onSurfaceVariant: '#3F4945',
          outline: '#6F7975',
          outlineVariant: '#BFC9C4',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#2B322F',
          inverseOnSurface: '#ECF2EE',
          inversePrimary: '#85D6C1',
          primaryFixed: '#A1F2DC',
          onPrimaryFixed: '#00201A',
          primaryFixedDim: '#85D6C1',
          onPrimaryFixedVariant: '#005143',
          secondaryFixed: '#CDE8DF',
          onSecondaryFixed: '#07201A',
          secondaryFixedDim: '#B1CCC3',
          onSecondaryFixedVariant: '#334B45',
          tertiaryFixed: '#C7E7FF',
          onTertiaryFixed: '#001E2E',
          tertiaryFixedDim: '#AACBE3',
          onTertiaryFixedVariant: '#2A4A5F',
          surfaceDim: '#D5DBD8',
          surfaceBright: '#F5FBF7',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#EFF5F1',
          surfaceContainer: '#E9EFEC',
          surfaceContainerHigh: '#E3EAE6',
          surfaceContainerHighest: '#DEE4E0',
        },
        dark: {
          primary: '#85D6C1',
          surfaceTint: '#85D6C1',
          onPrimary: '#00382E',
          primaryContainer: '#005143',
          onPrimaryContainer: '#A1F2DC',
          secondary: '#B1CCC3',
          onSecondary: '#1D352F',
          secondaryContainer: '#334B45',
          onSecondaryContainer: '#CDE8DF',
          tertiary: '#AACBE3',
          onTertiary: '#103447',
          tertiaryContainer: '#2A4A5F',
          onTertiaryContainer: '#C7E7FF',
          error: '#FFB4AB',
          onError: '#690005',
          errorContainer: '#93000A',
          onErrorContainer: '#FFDAD6',
          background: '#0E1513',
          onBackground: '#DEE4E0',
          surface: '#0E1513',
          onSurface: '#DEE4E0',
          surfaceVariant: '#3F4945',
          onSurfaceVariant: '#BFC9C4',
          outline: '#89938F',
          outlineVariant: '#3F4945',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#DEE4E0',
          inverseOnSurface: '#2B322F',
          inversePrimary: '#096B5A',
          primaryFixed: '#A1F2DC',
          onPrimaryFixed: '#00201A',
          primaryFixedDim: '#85D6C1',
          onPrimaryFixedVariant: '#005143',
          secondaryFixed: '#CDE8DF',
          onSecondaryFixed: '#07201A',
          secondaryFixedDim: '#B1CCC3',
          onSecondaryFixedVariant: '#334B45',
          tertiaryFixed: '#C7E7FF',
          onTertiaryFixed: '#001E2E',
          tertiaryFixedDim: '#AACBE3',
          onTertiaryFixedVariant: '#2A4A5F',
          surfaceDim: '#0E1513',
          surfaceBright: '#343B38',
          surfaceContainerLowest: '#090F0E',
          surfaceContainerLow: '#171D1B',
          surfaceContainer: '#1B211F',
          surfaceContainerHigh: '#252B29',
          surfaceContainerHighest: '#303634',
        },
      },
      boxShadow: {
        elevation1:
          '0px 1px 2px 0px rgba(0, 0, 0, 0.10), 0px 1px 3px 1px rgba(0, 0, 0, 0.05)',
        elevation2:
          '0px 2px 4px 0px rgba(0, 0, 0, 0.10), 0px 4px 6px 1px rgba(0, 0, 0, 0.05)',
        elevation3:
          '0px 4px 8px 3px rgba(0, 0, 0, 0.10), 0px 6px 10px 2px rgba(0, 0, 0, 0.05)',
      },
      borderRadius: {
        none: '0',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '24px',
        full: '9999px',
      },
      fontSize: {
        display: [
          '48px',
          {
            lineHeight: '56px',
            fontWeight: '700',
            letterSpacing: '-0.5px',
          },
        ],
        heading: [
          '32px',
          {
            lineHeight: '40px',
            fontWeight: '600',
            letterSpacing: '-0.25px',
          },
        ],
        body: [
          '16px',
          {
            lineHeight: '24px',
            fontWeight: '400',
            letterSpacing: '0',
          },
        ],
        small: [
          '14px',
          {
            lineHeight: '20px',
            fontWeight: '400',
            letterSpacing: '0.1px',
          },
        ],
      },
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
      },
    },
  },
  plugins: [],
};
