/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,jsx,js}'],
  theme: {
    extend: {
      fontFamily: {
        heading: ['Kanit', 'sans-serif'], // For headings
        body: ['Nunito', 'sans-serif'], // For body text
      },
      colors: {
        light: {
          primary: '#EC6171',
          surfaceTint: '#EC6171',
          onPrimary: '#FFFFFF',
          primaryContainer: '#F9DFCE',
          onPrimaryContainer: '#33062D',
          secondary: '#F08B85',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#FEF9F3',
          onSecondaryContainer: '#33062D',
          tertiary: '#BC1761',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#FFFFFF',
          onTertiaryContainer: '#33062D',
          error: '#E52A5F',
          onError: '#FFFFFF',
          errorContainer: '#F9DFCE',
          onErrorContainer: '#4F0940',
          background: '#FFFFFF',
          onBackground: '#33062D',
          surface: '#FFFFFF',
          onSurface: '#33062D',
          surfaceVariant: '#F9DFCE',
          onSurfaceVariant: '#BC1761',
          outline: '#F08B85',
          outlineVariant: '#F5BAAA',
          shadow: '#33062D',
          scrim: '#33062D',
          inverseSurface: '#4F0940',
          inverseOnSurface: '#FFFFFF',
          inversePrimary: '#F5BAAA',
          primaryFixed: '#F9DFCE',
          onPrimaryFixed: '#33062D',
          primaryFixedDim: '#F5BAAA',
          onPrimaryFixedVariant: '#BC1761',
          secondaryFixed: '#FEF9F3',
          onSecondaryFixed: '#33062D',
          secondaryFixedDim: '#F9DFCE',
          onSecondaryFixedVariant: '#F08B85',
          tertiaryFixed: '#FFFFFF',
          onTertiaryFixed: '#33062D',
          tertiaryFixedDim: '#FEF9F3',
          onTertiaryFixedVariant: '#BC1761',
          surfaceDim: '#FEF9F3',
          surfaceBright: '#FFFFFF',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#FFFFFF',
          surfaceContainer: '#FEF9F3',
          surfaceContainerHigh: '#F9DFCE',
          surfaceContainerHighest: '#F5BAAA',
        },
        dark: {
          primary: '#F5BAAA',
          surfaceTint: '#F5BAAA',
          onPrimary: '#4F0940',
          primaryContainer: '#BC1761',
          onPrimaryContainer: '#F9DFCE',
          secondary: '#F9DFCE',
          onSecondary: '#4F0940',
          secondaryContainer: '#F08B85',
          onSecondaryContainer: '#FEF9F3',
          tertiary: '#FEF9F3',
          onTertiary: '#33062D',
          tertiaryContainer: '#BC1761',
          onTertiaryContainer: '#FFFFFF',
          error: '#F08B85',
          onError: '#33062D',
          errorContainer: '#E52A5F',
          onErrorContainer: '#F9DFCE',
          background: '#33062D',
          onBackground: '#F5BAAA',
          surface: '#33062D',
          onSurface: '#F5BAAA',
          surfaceVariant: '#4F0940',
          onSurfaceVariant: '#F9DFCE',
          outline: '#F5BAAA',
          outlineVariant: '#4F0940',
          shadow: '#33062D',
          scrim: '#33062D',
          inverseSurface: '#F5BAAA',
          inverseOnSurface: '#4F0940',
          inversePrimary: '#BC1761',
          primaryFixed: '#F9DFCE',
          onPrimaryFixed: '#33062D',
          primaryFixedDim: '#F5BAAA',
          onPrimaryFixedVariant: '#BC1761',
          secondaryFixed: '#FEF9F3',
          onSecondaryFixed: '#33062D',
          secondaryFixedDim: '#F9DFCE',
          onSecondaryFixedVariant: '#F08B85',
          tertiaryFixed: '#FFFFFF',
          onTertiaryFixed: '#33062D',
          tertiaryFixedDim: '#FEF9F3',
          onTertiaryFixedVariant: '#BC1761',
          surfaceDim: '#33062D',
          surfaceBright: '#851058',
          surfaceContainerLowest: '#33062D',
          surfaceContainerLow: '#4F0940',
          surfaceContainer: '#4F0940',
          surfaceContainerHigh: '#851058',
          surfaceContainerHighest: '#BC1761',
        },
      },
      boxShadow: {
        elevation1:
          '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)',
        elevation2:
          '0px 1px 2px 0px rgba(0, 0, 0, 0.30), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)',
        elevation3:
          '0px 4px 8px 3px rgba(0, 0, 0, 0.15), 0px 1px 3px 0px rgba(0, 0, 0, 0.30)',
        elevation4:
          '0px 6px 10px 4px rgba(0, 0, 0, 0.15), 0px 2px 3px 0px rgba(0, 0, 0, 0.30)',
        elevation5:
          '0px 8px 12px 6px rgba(0, 0, 0, 0.15), 0px 4px 4px 0px rgba(0, 0, 0, 0.30)',
      },
      borderRadius: {
        none: '0',
        extraSmall: '4px',
        small: '8px',
        medium: '12px',
        large: '16px',
        extraLarge: '28px',
        full: '1000px',
      },
      fontSize: {
        displayLarge: [
          '57px',
          {
            fontWeight: '400',
            lineHeight: '64px',
            letterSpacing: '-0.25px',
          },
        ],
        displayMedium: [
          '45px',
          {
            fontWeight: '400',
            lineHeight: '52px',
            letterSpacing: '0',
          },
        ],
        displaySmall: [
          '36px',
          {
            fontWeight: '400',
            lineHeight: '44px',
            letterSpacing: '0',
          },
        ],
        headlineLarge: [
          '32px',
          {
            fontWeight: '400',
            lineHeight: '40px',
            letterSpacing: '0',
          },
        ],
        headlineMedium: [
          '28px',
          {
            fontWeight: '400',
            lineHeight: '36px',
            letterSpacing: '0',
          },
        ],
        headlineSmall: [
          '24px',
          {
            fontWeight: '400',
            lineHeight: '32px',
            letterSpacing: '0',
          },
        ],
        titleLarge: [
          '22px',
          {
            fontWeight: '400',
            lineHeight: '28px',
            letterSpacing: '0',
          },
        ],
        titleMedium: [
          '16px',
          {
            fontWeight: '500',
            lineHeight: '24px',
            letterSpacing: '0.15px',
          },
        ],
        titleSmall: [
          '14px',
          {
            fontWeight: '500',
            lineHeight: '20px',
            letterSpacing: '0.1px',
          },
        ],
        bodyLarge: [
          '16px',
          {
            fontWeight: '400',
            lineHeight: '24px',
            letterSpacing: '0.5px',
          },
        ],
        bodyMedium: [
          '14px',
          {
            fontWeight: '400',
            lineHeight: '20px',
            letterSpacing: '0.25px',
          },
        ],
        bodySmall: [
          '12px',
          {
            fontWeight: '400',
            lineHeight: '16px',
            letterSpacing: '0.4px',
          },
        ],
        labelLarge: [
          '14px',
          {
            fontWeight: '500',
            lineHeight: '20px',
            letterSpacing: '0.1px',
          },
        ],
        labelMedium: [
          '12px',
          {
            fontWeight: '500',
            lineHeight: '16px',
            letterSpacing: '0.5px',
          },
        ],
        labelSmall: [
          '11px',
          {
            fontWeight: '500',
            lineHeight: '16px',
            letterSpacing: '0.5px',
          },
        ],
      },
      transitionDuration: {
        short1: '50ms',
        short2: '100ms',
        short3: '150ms',
        short4: '200ms',
        medium1: '250ms',
        medium2: '300ms',
        medium3: '350ms',
        medium4: '400ms',
        long1: '450ms',
        long2: '500ms',
        long3: '550ms',
        long4: '600ms',
        extraLong1: '700ms',
        extraLong2: '800ms',
        extraLong3: '900ms',
        extraLong4: '1000ms',
      },
      transitionDelay: {
        short1: '50ms',
        short2: '100ms',
        short3: '150ms',
        short4: '200ms',
        medium1: '250ms',
        medium2: '300ms',
        medium3: '350ms',
        medium4: '400ms',
        long1: '450ms',
        long2: '500ms',
        long3: '550ms',
        long4: '600ms',
        extraLong1: '700ms',
        extraLong2: '800ms',
        extraLong3: '900ms',
        extraLong4: '1000ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
        standardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
        standardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
        emphasized: 'cubic-bezier(0.2, 0, 0, 1.0)',
        emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
        emphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
        legacy: 'cubic-bezier(0.4, 0, 0.2, 1.0)',
        legacyDecelerate: 'cubic-bezier(0, 0, 0.2, 1)',
        legacyAccelerate: 'cubic-bezier(0.4, 0, 1, 1)',
        linear: 'cubic-bezier(0, 0, 1, 1)',
      },
      animation: {
        first: "moveVertical 30s ease infinite",
        second: "moveInCircle 20s reverse infinite",
        third: "moveInCircle 40s linear infinite",
        fourth: "moveHorizontal 40s ease infinite",
        fifth: "moveInCircle 20s ease infinite",
      },
      keyframes: {
        moveHorizontal: {
          "0%": {
            transform: "translateX(-50%) translateY(-10%)",
          },
          "50%": {
            transform: "translateX(50%) translateY(10%)",
          },
          "100%": {
            transform: "translateX(-50%) translateY(-10%)",
          },
        },
        moveInCircle: {
          "0%": {
            transform: "rotate(0deg)",
          },
          "50%": {
            transform: "rotate(180deg)",
          },
          "100%": {
            transform: "rotate(360deg)",
          },
        },
        moveVertical: {
          "0%": {
            transform: "translateY(-50%)",
          },
          "50%": {
            transform: "translateY(50%)",
          },
          "100%": {
            transform: "translateY(-50%)",
          },
        },
      },
    },
  },
  plugins: [],
};
